<<<<<<< HEAD
title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
=======
theme: jekyll-theme-cayman
>>>>>>> 51ffa03073eb74c14123509828956e8c7477796d
