theme: jekyll-theme-cayman
title: Kashish Khare
description: I strongly believe that an individual with exceptional analytical abilities and can-do attitude can innovate, collaborate and excel anywhere.
email: khare.kashish@gmail.com
phone: (201) 464-3242
linkedin: www.linkedin.com/in/kashishkhare